module.exports = {
  duplicateList: [
    1, 1, 1, 5, 2, 3, 4, 3, 3, 3, 3, 3, 3, 7, 8, 5, 4, 9, 0, 1, 3, 2, 6, 7, 5,
    4, 4, 7, 8, 8, 0, 1, 2, 3, 1,
  ],
  professionOrder: {
    systemAnalytics: 25,
    engineer: 20,
    productOwner: 15,
    freelancer: 10,
    student: 5,
  },
  users: [
    {
      firstName: "Alice",
      lastName: "Smith",
      customerID: "129473",
      note: "Needs follow-up",
      profession: "student",
    },
    {
      firstName: "Bob",
      lastName: "Johnson",
      customerID: "584210",
      note: "",
      profession: "freelancer",
    },
    {
      firstName: "Charlie",
      lastName: "",
      customerID: "364582",
      note: "Important client",
      profession: "engineer",
    },
    {
      firstName: "David",
      lastName: "Brown",
      customerID: "923481",
      note: "New customer",
      profession: "systemAnalytics",
    },
    {
      firstName: "Eve",
      lastName: "Jones",
      customerID: "276594",
      note: "",
      profession: "productOwner",
    },
    {
      firstName: "Frank",
      lastName: "Miller",
      customerID: "473182",
      note: "High priority",
      profession: "freelancer",
    },
    {
      firstName: "John",
      lastName: "Davis",
      customerID: "849273",
      note: "",
      profession: "student",
    },
    {
      firstName: "Jane",
      lastName: "Garcia",
      customerID: "157362",
      note: "Needs follow-up",
      profession: "engineer",
    },
    {
      firstName: "Alice",
      lastName: "",
      customerID: "538472",
      note: "Important client",
      profession: "systemAnalytics",
    },
    {
      firstName: "Charlie",
      lastName: "Johnson",
      customerID: "672193",
      note: "",
      profession: "productOwner",
    },
  ],
};
